version: '3'

services:
  database:
    image: mysql:9.0
    volumes:
      - order_database:/var/lib/mysql
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: Ex@mple12345

volumes:
  order_database:
